import 'reflect-metadata';
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { NestFactory } from '@nestjs/core';
import type { OpenAPIObject } from '@nestjs/swagger';

import { loadEnvFile } from '@/config/load-env';
import { buildOpenApiDocument } from '@/config/openapi';

/**
 * Writes docs/openapi.json and docs/API_CONTRACT.md from the live route
 * metadata.
 *
 *   npm run docs:api --workspace @isd/api
 *
 * The interactive Swagger UI is off in production by design (§3.3) — an
 * always-on schema browser enumerates every admin route and validation rule
 * for anyone who asks. These committed files are the answer for the people who
 * legitimately need the contract: the two frontend developers, and anyone
 * picking the project up later.
 *
 * Generated rather than hand-written, so it cannot drift from the code. The
 * plan asks for docs/API_CONTRACT.md on day 2 of Phase 0 precisely so both
 * frontends can build against it (§17.1).
 */

/** Nest needs a real app to read the decorator metadata, but never listens. */
async function createDocument(): Promise<OpenAPIObject> {
  loadEnvFile();

  // The document only needs route metadata, so the app is never started and
  // never connects to anything. These stand in for the real values so the env
  // schema passes without requiring a configured machine to generate docs.
  const placeholders: Record<string, string> = {
    NODE_ENV: 'development',
    MONGODB_URI: 'mongodb://127.0.0.1:27017',
    MONGODB_DB_NAME: 'docs',
    JWT_ACCESS_SECRET: 'x'.repeat(32),
    JWT_REFRESH_SECRET: 'y'.repeat(32),
    CLOUDINARY_CLOUD_NAME: 'docs',
    CLOUDINARY_API_KEY: 'docs',
    CLOUDINARY_API_SECRET: 'docs',
    STOREFRONT_ORIGIN: 'http://localhost:3000',
    ADMIN_ORIGIN: 'http://localhost:5173',
    STOREFRONT_REVALIDATE_URL: 'http://localhost:3000/api/revalidate',
    REVALIDATE_SECRET: 'z'.repeat(20),
    TURNSTILE_SECRET_KEY: 'docs',
    QUOTATION_NOTIFY_ENABLED: 'false',
  };

  for (const [key, value] of Object.entries(placeholders)) {
    process.env[key] ??= value;
  }

  const { AppModule } = await import('@/app.module');
  const app = await NestFactory.create(AppModule, { logger: false, preview: true });

  const document = buildOpenApiDocument(app);
  await app.close();

  return document;
}

/** Renders the spec as a scannable markdown reference. */
function toMarkdown(document: OpenAPIObject): string {
  const byTag = new Map<string, string[]>();

  for (const [path, item] of Object.entries(document.paths)) {
    for (const [method, operation] of Object.entries(item as Record<string, unknown>)) {
      if (!['get', 'post', 'patch', 'put', 'delete'].includes(method)) continue;

      const op = operation as {
        tags?: string[];
        summary?: string;
        security?: unknown[];
      };

      const tag = op.tags?.[0] ?? 'Other';
      // A route is protected unless it opted out with @Public().
      const locked = path.includes('/admin/') ? ' 🔒' : '';

      const rows = byTag.get(tag) ?? [];
      rows.push(`| \`${method.toUpperCase()}\` | \`${path}\`${locked} | ${op.summary ?? ''} |`);
      byTag.set(tag, rows);
    }
  }

  const sections = [...byTag.entries()].map(([tag, rows]) =>
    [
      `### ${tag}`,
      '',
      '| Method | Path | Purpose |',
      '| ------ | ---- | ------- |',
      ...rows,
      '',
    ].join('\n'),
  );

  const total = [...byTag.values()].reduce((sum, rows) => sum + rows.length, 0);

  return [
    '# API contract',
    '',
    '<!-- Generated by `npm run docs:api --workspace @isd/api`. Do not edit by hand. -->',
    '',
    `Base path \`/api/v1\` · ${total} endpoints · generated from the route metadata,`,
    'so it cannot drift from the code.',
    '',
    'Routes marked 🔒 require an authenticated admin session.',
    '',
    '## Response envelope',
    '',
    'Every response has the same shape (PROJECT_PLAN.md §8):',
    '',
    '```jsonc',
    '{ "success": true,  "data": {}, "meta": {} }',
    '{ "success": false, "error": { "code": "VALIDATION_ERROR", "message": "…", "details": [] } }',
    '```',
    '',
    'Listing endpoints add pagination and facet counts to `meta`:',
    '',
    '```jsonc',
    '"meta": {',
    '  "page": 1, "limit": 24, "total": 1049, "totalPages": 44,',
    '  "facets": { "categories": [...], "brands": [...], "industries": [...] }',
    '}',
    '```',
    '',
    '## Authentication',
    '',
    'Admin routes require a JWT in an httpOnly cookie (`isd_at`) from',
    '`POST /admin/auth/login`. A bearer token is accepted as a secondary source',
    'for tooling. Refresh rotates the token and invalidates the previous one.',
    '',
    'An account with `mustChangePassword` set can reach only `/admin/auth/me`,',
    '`/admin/auth/change-password` and `/admin/auth/logout` until it is cleared.',
    '',
    '## There are no prices',
    '',
    'This is a quotation-only platform. No endpoint accepts or returns a price,',
    'and none should be added — see CLAUDE.md §1.',
    '',
    '## Endpoints',
    '',
    ...sections,
    '## Interactive docs',
    '',
    'Swagger UI runs at `/api/v1/docs` outside production. It is off in',
    'production by default because it enumerates every route and validation rule',
    '(§3.3); set `SWAGGER_ENABLED=true` to serve it anyway.',
    '',
    'The machine-readable spec is `docs/openapi.json` — import it into Postman,',
    'Insomnia or an OpenAPI client generator.',
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const document = await createDocument();

  const docsDir = resolve(__dirname, '..', '..', '..', '..', '..', 'docs');
  mkdirSync(docsDir, { recursive: true });

  const specPath = resolve(docsDir, 'openapi.json');
  const contractPath = resolve(docsDir, 'API_CONTRACT.md');

  writeFileSync(specPath, `${JSON.stringify(document, null, 2)}\n`);
  writeFileSync(contractPath, toMarkdown(document));

  const count = Object.values(document.paths).reduce(
    (sum, item) =>
      sum +
      Object.keys(item as Record<string, unknown>).filter((key) =>
        ['get', 'post', 'patch', 'put', 'delete'].includes(key),
      ).length,
    0,
  );

  console.log(`Documented ${count} endpoints:`);
  console.log(`  ${specPath}`);
  console.log(`  ${contractPath}`);
}

main().catch((error: Error) => {
  console.error(`Could not generate the API docs: ${error.message}`);
  process.exitCode = 1;
});
